# 
Question-1

a) False, because matrix addition and scalar multiplication of all nxn matrices gives vector space of R^n not R. 

b) True, the solution for the equation is the vectors (0.5,1,0),(-0.5,0,1) which is a subset in R^3

c) True. Defiition of linear span

d) False, Since the span of the all the vectors is only (1,3,5)

e) False, conditions are not met.

f) True, linear span of the basis gives the vector space. “Minimum set of vectors that spans the entire space,is a 
basis”

g) True, when  {(1, 1), (1, −1)} is multiplied by (2, −1), it give (1,3). Hence(2,-1) is a coordinate vector

h) False, Linear functional is R^n -> R. Not R^n -> R^n

i) True

j) False, The dot product of the two vectors is not 0(Zero) but is 1, hence not orthogonal

In [17]:
import numpy as np
from math import sqrt


a = np.array([1,1,0])
b = np.array([0,1,1])

# a
res = (2*a)-(3*b)
print('Computation: {0}'.format(res))
# b
c = np.concatenate((a,b))
print('Concated matrix: {0}'.format(c))
# c
t1=[]
t1.append(a[1])
t1.append(b[1])
t1.append(b[2])
t1 = np.array(t1)
print('array (a2,b2,b3): {0}'.format(t1))

# d
dist = np.linalg.norm(a-b)
print('distance: {0}'.format(dist))

# e
def mod_vect(a):
    res = sqrt(a[0]+a[1]+a[2])
    return res

t1 = a+b
t2 = a-b

mod_t1 = mod_vect(t1)
mod_t2 = mod_vect(t2)
x_t = t1.T

# angle formula
angle = np.arccos((x_t*t2)/mod_t1*mod_t2)
print('Angle: {0}\n'.format(angle))

# Question 3

symm = np.array([[2,4,4],[4,8,8],[4,8,8]])
print('Symmetric: {0}'.format(symm))
print('Sub matrix of Symmetric: {0}'.format(symm[0:3:2, 0:3:2]))

skew_symm = np.array([[0,1,-2],[-1,0,3],[2,-3,0]])
print('Skew Symmetric: {0}'.format(skew_symm))
print('Sub Matrix Skew Symmetric: {0}'.format(skew_symm[0:3:2, 0:3:2]))

stoch = np.array([[0.90,0.01,0.09],[0.01,0.90,0.01],[0.09,0.09,0.90]])
print('stochaistic matrix: {0}'.format(stoch))
print('Sub stochaistic matrix: {0}'.format(stoch[0:3:2, 0:3:2]))

hankel = np.array([[1,2,3],[2,3,4],[3,4,5]])
print('Hankel: {0}'.format(hankel))
print('Sub Hankel: {0}'.format(hankel[0:3:2, 0:3:2]))

# Question 4
a = np.array([[1,-1,0,1,3],[2,3,-1,-4,4],[1,0,1,1,-2]])

# Assuming that D is a 5x3 matrix
D = a.T

least=[]
for i in range(0,len(D)):    
    least.append(np.linalg.norm(D[i]-[1,1,1]))
arr = D[least.index(min(least))]
print('Point with least distance from (1,1,1) in dataset D: {0}'.format(arr))

standard_deviation = np.std(D,axis=0)
mean= np.mean(D,axis=0)

print('Standard Deviation: {0}\n Mean: {1}'.format(standard_deviation,mean))

Computation: [ 2 -1 -3]
Concated matrix: [1 1 0 0 1 1]
array (a2,b2,b3): [1 1 1]
distance: 1.4142135623730951
Angle: [1.57079633 1.57079633 1.57079633]

Symmetric: [[2 4 4]
 [4 8 8]
 [4 8 8]]
Sub matrix of Symmetric: [[2 4]
 [4 8]]
Skew Symmetric: [[ 0  1 -2]
 [-1  0  3]
 [ 2 -3  0]]
Sub Matrix Skew Symmetric: [[ 0 -2]
 [ 2  0]]
stochaistic matrix: [[0.9  0.01 0.09]
 [0.01 0.9  0.01]
 [0.09 0.09 0.9 ]]
Sub stochaistic matrix: [[0.9  0.09]
 [0.09 0.9 ]]
Hankel: [[1 2 3]
 [2 3 4]
 [3 4 5]]
Sub Hankel: [[1 3]
 [3 5]]
Point with least distance from (1,1,1) in dataset D: [1 2 1]
Standard Deviation: [1.32664992 2.92574777 1.16619038]
 Mean: [0.8 0.8 0.2]
